global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-examples
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  reporting: true
tests:
  json-master:
    parameter_input: workload-master.json
    regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    template_file: workload-json-master.template
  yaml-master:
    parameter_input: workload-master.json
    regions:
    - eu-west-1
    - eu-west-2
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    template_file: workload-yaml-master.template
